# Generated by Django 5.2.4 on 2026-04-25 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locatarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Espaco",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("endereco", models.TextField()),
                ("cidade", models.CharField(max_length=100)),
                ("cep", models.CharField(max_length=8)),
                ("capacidade", models.IntegerField()),
                ("preco_por_hora", models.DecimalField(decimal_places=2, max_digits=10)),
                ("disponivel", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "locatario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="espacos", to="locatarios.locatario"
                    ),
                ),
            ],
            options={
                "db_table": "espacos",
            },
        ),
    ]
