services:
  db:
    container_name: espaco_livre_db_production
    volumes:
      - postgres_data_production:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env.production
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    deploy:
      resources:
        limits:
          memory: 1g

  backend:
    build:
      target: production
    container_name: espaco_livre_backend_production
    env_file:
      - ./backend/.env.production

  frontend:
    build:
      target: production
    container_name: espaco_livre_frontend_production
    env_file:
      - ./frontend/.env.production

  ollama:
    container_name: espaco_livre_ollama_production

  ollama-puller:
    container_name: espaco_livre_ollama_puller_production

volumes:
  postgres_data_production:
