# Generated by Django 5.0.4 on 2025-03-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alocador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254)),
                ('senha', models.CharField(max_length=100)),
                ('nome_usuario', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('idade', models.IntegerField()),
                ('endereco_residencial', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('aceitar_termos', models.BooleanField(default=False)),
                ('cep', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254)),
                ('senha', models.CharField(max_length=100)),
                ('nome_usuario', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('idade', models.IntegerField()),
                ('endereco_residencial', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=9)),
                ('tipo_ocupacao', models.CharField(blank=True, choices=[('startup', 'Startup'), ('influencer', 'Influencer'), ('produtor', 'Produtor'), ('gerente', 'Gerente'), ('freelancer', 'Freelancer'), ('fotografo', 'Fotógrafo')], max_length=50)),
                ('frequencia_uso', models.CharField(blank=True, choices=[('ocasional', 'Ocasional'), ('semanal', 'Semanal'), ('diario', 'Diário'), ('mensal', 'Mensal')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254)),
                ('senha', models.CharField(max_length=100)),
                ('salvar_senha', models.BooleanField(default=False)),
            ],
        ),
    ]
