# Generated by Django 5.0.4 on 2025-03-08 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alocador',
            new_name='AuthAlocador',
        ),
        migrations.RenameModel(
            old_name='Cliente',
            new_name='AuthCliente',
        ),
        migrations.RenameModel(
            old_name='Login',
            new_name='AuthLogin',
        ),
    ]
