# Generated by Django 5.1.7 on 2025-03-17 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_rename_alocador_authalocador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authlogin',
            old_name='email',
            new_name='nome_usuario',
        ),
    ]
