# Generated by Django 5.1.7 on 2025-03-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_rename_email_authlogin_nome_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authlogin',
            name='nome_usuario',
            field=models.CharField(max_length=100),
        ),
    ]
