# Generated by Django 5.1.7 on 2025-03-21 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_authlogin_nome_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authalocador',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='authalocador',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='authalocador',
            name='idade',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='authalocador',
            name='senha',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='authcliente',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='authcliente',
            name='idade',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='authcliente',
            name='senha',
            field=models.CharField(max_length=128),
        ),
    ]
