# Generated by Django 5.2.4 on 2026-04-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Locatario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_usuario", models.CharField(max_length=100)),
                ("senha", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefone", models.CharField(blank=True, max_length=20, null=True)),
                ("idade", models.IntegerField(blank=True, null=True)),
                ("endereco_residencial", models.TextField(blank=True, null=True)),
                ("cidade", models.CharField(blank=True, max_length=100, null=True)),
                ("cpf", models.CharField(max_length=11, unique=True)),
                ("cep", models.CharField(blank=True, max_length=8, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "locatarios",
            },
        ),
    ]
